### ISSUE TITLE
Copy edit

### ISSUE THREAD

**Issue by MissPhilbin** [raspberrypilearning/faq-guide#2]
@LornaLynch I've just completed the copy for 10 FAQ for the help section. Would you mind weaving your magic on my terrible copy please?

**Comment by LornaLynch** [comment]
Coming up :)

**Comment by LornaLynch** [comment]
Some of the file numbers are at odds with the number of the FAQ itself: I'm guessing this is to do with how they format on the website, and that it isn't a problem?

**Comment by MissPhilbin** [comment]
Yeah I didn't have time to go through an rename them all so I just skipped it.

**Comment by LornaLynch** [comment]
No worries: I've changed the numbers in a couple of instances where they were out of sync with the table of contents numbering, but I haven't bothered with the file names. All done!
