### ISSUE TITLE
Link no longer has a page (Pi3 PSU)

### ISSUE THREAD

**Issue by bsimmo** [raspberrypilearning/faq-guide#5]
The Pi3 link to official PSU is now a 404 page.

**Comment by lawsie** [comment]
Just looked and it is working fine for me?
https://www.raspberrypi.org/learning/troubleshooting-guide/pi-3-power-supply/ links to https://www.raspberrypi.org/products/raspberry-pi-universal-power-supply/ ?

Closing the issue, but feel free to reopen if I have misunderstood.

**Comment by bsimmo** [comment]
Nope works now for me too.
 Good chance something was fixed altered in the past months :-)
